.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2015 Julian Gilbey <J.Gilbey@maths.cam.ac.uk>, <jdg@debian.org>
.\" For licence conditions, see COPYING
.TH JIGSAW-GENERATOR 1 "December 18, 2015"
.SH NAME
jigsaw-generator \- program to generate jigsaws and card sort activities
.SH SYNOPSIS
.B jigsaw-generator
.RI [ options ] " puzzlefile[.yaml]"
.SH DESCRIPTION
This manual page briefly documents the
.B jigsaw-generator
command.
.PP
.B jigsaw-generator
is a program that reads a YAML data file and from it creates a
"jigsaw" puzzle or card sorting activity, generally intended for
classroom use.  For more information, see the documentation in
/usr/share/doc/jigsaw.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
.PP
A summary of options is included below.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version information.
.TP
.BI "\-o " OUTPUT ", \-\-output " OUTPUT
Use
.I OUTPUT
as the basename of the output files, rather than puzzlefile.
.TP
.B \-\-noclean, \-\-no-clean
Do not clean the auxiliary files which are created (such as the LaTeX
file used to generate the PDF versions of the puzzle).
.TP
.B \-\-clean
Do clean the auxiliary files; this is the default behaviour.
.TP
.BI "\-\-latex " LATEX
The LaTeX variant to run.  The default is pdflatex, but this default
can be overridden by the template file used.
.TP
.B \-\-nomakepdf, \-\-no-makepdf
Do not make PDF output files.
.TP
.B \-\-makepdf
Make PDF output files; this is the default behaviour.
.TP
.B \-\-nomakemd, \-\-no-makemd
Do not make Markdown output files.
.TP
.B \-\-makemd
Make Markdown output files; this is the default behaviour.
.TP
.BI "\-\-texfilter " TEXFILTER
Run the LaTeX file through
.I TEXFILTER
before running pdflatex (or whichever LaTeX variant is being used).
This filter should accept the original LaTeX file on its standard input
and output the filtered file on its standard output.
.TP
.BI "\-\-mdfilter " MDFILTER
Run the Markdown file through
.I MDFILTER
after producing it.
This filter should accept the original Markdown file on its standard input
and output the filtered file on its standard output.
.SH CONFIGURATION FILES
The program reads configuration files and template files when processing
the template file.  For full information, see the complete documention.
.SH SEE ALSO
The program is documented fully by the documentation included with the
package, typically installed in /usr/share/doc/jigsaw-generator or
/usr/local/share/doc/jigsaw-generator.
