.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2015 Julian Gilbey <J.Gilbey@maths.cam.ac.uk>, <jdg@debian.org>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH JIGSAW-GENERATOR 1 "August 27, 2015"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
jigsaw-generator \- program to generate jigsaws and card sort activities
.SH SYNOPSIS
.B jigsaw-generator
.RI [ options ] " file"
.SH DESCRIPTION
This manual page briefly documents the
.B jigsaw-generator
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invoke bold face and italics,
.\" respectively.
.B jigsaw-generator
is a program that reads a YAML data file and from it creates a
"jigsaw" puzzle or card sorting activity, generally intended for
classroom use.  For more information, see the documentation in
/usr/share/doc/jigsaw.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
.PP
A summary of options is included below.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.
.SH SEE ALSO
The programs are documented fully by the documentation found in the
package, typically installed in /usr/share/doc/jigsaw.
