Document: jigsaw-generator
Title: Debian jigsaw-generator Manual
Author: <insert document author here>
Abstract: This manual describes what jigsaw-generator is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/jigsaw-generator/jigsaw-generator.sgml.gz

Format: postscript
Files: /usr/share/doc/jigsaw-generator/jigsaw-generator.ps.gz

Format: text
Files: /usr/share/doc/jigsaw-generator/jigsaw-generator.text.gz

Format: HTML
Index: /usr/share/doc/jigsaw-generator/html/index.html
Files: /usr/share/doc/jigsaw-generator/html/*.html
