#! /usr/bin/env python3

"""
Filter program for handling CMEP LaTeX jigsaw files

Usage: This program takes a LaTeX file on stdin and outputs a
filtered version on stdout

Actions: \includegraphics{XXX.png} has the .png stripped, so that
LaTeX can find XXX.pdf instead, if it exists.  Also, if XXX.svg exists
but XXX.pdf does not, then inkscape is called to process it.  (This
filter will not refresh the pdf file if the svg is updated, for
safety purposes.)
"""

import fileinput
import re
import os
import os.path
import sys
import subprocess

img_re = re.compile(r'(\\image(?:cap)?)\{(.*?)\.png\}')

for line in fileinput.input():
    imgre = img_re.search(line)
    while imgre:
        imgbase = imgre.group(2)
        if (not os.access(imgbase + '.pdf', os.R_OK) and
            os.access(imgbase + '.svg', os.R_OK)):
            svg = os.path.join(os.getcwd(), imgbase + '.svg')
            pdf = os.path.join(os.getcwd(), imgbase + '.pdf')
            try:
                inkout = subprocess.check_output(['inkscape', '-z', '-D',
                                                  '--export-pdf', pdf, svg])
            except subprocess.CalledProcessError as cpe:
                sys.exit('inkscape failed to convert %s with return code %s, '
                         'aborting' % (imgbase, cpe.returncode))
        line = img_re.sub(r'\1{\2}', line)
        imgre = img_re.search(line)
    print(line, end='')

    
            
